name: Deploy website on Azure VM

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v4

      - name: Verificar se o secret DEPLOY_KEY est치 definido
        run: |
          if [ -z "${{ secrets.DEPLOY_KEY }}" ]; then
            echo "ERRO: DEPLOY_KEY est치 VAZIO."
            exit 1
          else
            echo "DEPLOY_KEY est치 DEFINIDO."
          fi

      - name: Configurar chave SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Instalar Apache e publicar site
        run: |
          ssh -o StrictHostKeyChecking=no gestor@74.161.42.40 "sudo apt update && sudo apt install -y apache2"
          scp -o StrictHostKeyChecking=no -r ./ gestor@74.161.42.40:/var/www/html/
          ssh -o StrictHostKeyChecking=no gestor@74.161.42.40 "sudo chown -R www-data:www-data /var/www/html && sudo systemctl restart apache2"
